[mysql]
# 数据库连接信息
host = 192.168.1.109
port = 3306
user = root
password = 123456
database = stock
charset = utf8mb4

# 连接池/超时配置（可选）
connect_timeout = 10
read_timeout = 30
write_timeout = 30


[redis]
host = 192.168.1.109
port = 6379
password = 123456
db = 0
max_connections = 20
timeout = 5
decode_responses = True


[baostock]
stock_fields = date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
day_frequency = d
week_frequency = w
month_frequency = m
adjustflag = 3