[mysql]
# 数据库连接信息
host = 192.168.1.109
port = 3306
user = root
password = 123456
database = stock
charset = utf8mb4

# 连接池/超时配置（可选）
connect_timeout = 10
read_timeout = 600
write_timeout = 600


[redis]
# Redis 容器配置（通过宿主机访问）
host = 192.168.1.109
port = 6379
password = 123456
db = 0
max_connections = 20
timeout = 5
decode_responses = True


[baostock]
min_stock_fields = date,code,open,high,low,close,volume,amount,time,adjustflag
date_stock_fields = date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,peTTM,pbMRQ,psTTM,pcfNcfTTM,isST
week_stock_fields = date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
month_stock_fields = date,code,open,high,low,close,volume,amount,adjustflag,turn,pctChg
date_index_stock_fields = date,code,open,high,low,close,preclose,volume,amount,pctChg
week_index_stock_fields = date,code,open,high,low,close,volume,amount,pctChg
month_index_stock_fields = date,code,open,high,low,close,volume,amount,pctChg
day_frequency = d
week_frequency = w
month_frequency = m
min_frequency = 15
adjustflag = 2